### PR TITLE
Python impl

### PR DESCRIPTION
**Pull request by andreaTP**
WIP to evaluate the effort to port the original implementation to Python.

### CODE REVIEW

**Comment by andreaTP** [comment]
As this is the first implementation other than the original one there are a few changes/improvements to the testing setup.
As soon as we consolidate and close the remaining issues I'll add detailed instructions on how to add a new language.

**Comment by andreaTP** [comment]
FYI: getting to Level 4 and passing all of the tests took just a few hours 🙂  (with the initial help of ChatGPT).
This was an experiment to evaluate the effort of adding more languages, I'm pretty satisfied!

cc. @baywet @darrelmiller

**Comment by baywet** [comment]
my python is weak. Maybe @samwelkanda can help with this one?
Sam: the goal here is to come up with a bunch of canonical implementations that'd be hosted under the organization that owns the RFC and would be really lightweight. Finding good URL template implementations that don't bring tons of other things and are maintained has been a challenge across languages.

**Comment by andreaTP** [comment]
probably going to drop this implementation, as I'm going to care a bit more about performance.

**Comment by andreaTP** [comment]
Superseded by #11

**Pull request closed without merging**
